# Generated by Django 5.0 on 2024-06-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='cod',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
