# Generated by Django 5.0 on 2024-06-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0002_shutdown_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_list1',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_list2',
            field=models.JSONField(null=True),
        ),
    ]
