# Generated by Django 5.0 on 2024-06-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0003_banner_banner_list1_banner_banner_list2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='used_products',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
