# Generated by Django 5.0 on 2024-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0004_shutdown_used_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutdown',
            name='online_payment',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
