# Generated by Django 4.0.4 on 2024-05-02 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ordermodel',
            name='business_pickup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 9), null=True),
        ),
    ]
