# Generated by Django 4.0.4 on 2024-05-04 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_ordermodel_business_pickup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 11), null=True),
        ),
    ]
