# Generated by Django 5.0 on 2024-05-21 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_ordermodel_expected_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='razorpay_order_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='razorpay_payment_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='razorpay_signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 28), null=True),
        ),
    ]
