# Generated by Django 5.0 on 2024-06-08 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_ordermodel_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 6, 15), null=True),
        ),
    ]
