# Generated by Django 5.0 on 2024-06-10 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_ordermodel_expected_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='normal_delivery_assign',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 6, 17), null=True),
        ),
    ]
