# Generated by Django 4.0.4 on 2024-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_id',
            field=models.TextField(null=True),
        ),
    ]
