# Generated by Django 4.0.4 on 2024-05-05 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_notify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 12), null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='payment_status',
            field=models.TextField(default='', null=True),
        ),
    ]
