# Generated by Django 5.0 on 2024-06-13 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_ordermodel_normal_delivery_assign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 6, 20), null=True),
        ),
    ]
