# Generated by Django 4.0.4 on 2024-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_ordermodel_expected_deliverydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
