# Generated by Django 4.0.4 on 2024-05-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_id',
        ),
    ]
