# Generated by Django 5.0 on 2024-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_ordermodel_expected_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
