# Generated by Django 4.0.4 on 2024-05-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_notification_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
    ]
