# Generated by Django 5.0 on 2024-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_businessmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
