# Generated by Django 4.0.4 on 2024-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_notification_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.TextField(null=True),
        ),
    ]
