# Generated by Django 5.0 on 2024-07-10 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_businessmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='earnings',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 7, 17), null=True),
        ),
    ]
